export const API = {
  // GET
  GET_USERS:              'get-users',
  GET_BATCH:              'get-batch',
  GET_LICENSE:            'get-license',
  GET_PROJECT:            'get-project',
  GET_PROJECTS:           'get-projects',
  GET_CLIENTS:            'get-clients',
  GET_USERNAMES:          'get-usernames',
  GET_PERSONAE:           'get-personae',
  GET_WORKBOOK:           'get-workbook',
  GET_TEST_ACCESS:        'get-test-access',
  // POST
  DISABLE_USER:           'disable-user',
  ACTIVATE_USER:          'activate-user',
  DELETE_USER:            'delete-user',
  RESET_USER:             'reset-user',
  CHANGE_PASSWORD:        'change-password',
  NEW_USER:               'new-user',
  NEW_PROJECT:            'new-project',
  NEW_CLIENT_PROJECT:     'new-client-project',
  UPDATE_LOGO:            'update-logo',
  CHANGE_ADMIN:           'change-admin',
  ADD_BATCH:              'add-batch',
  SAVE_DEPLOYMENT:        'save-deployment',
  SAVE_MODULES:           'save-modules',
  SAVE_CSV_DATA:          'save-csv-data',
};
